### ISSUE TITLE
Add component : Map locate

### ISSUE THREAD

**Issue by PanierAvide** [osm-ui/react#1]
We can create a component which allows user, when clicked, to see on the Map component where he/she is. It can be based for example on https://github.com/domoritz/leaflet-locatecontrol

**Comment by GuillaumeAmat** [comment]
As I just saw in the [react-leaflet](https://github.com/PaulLeCam/react-leaflet) repository, it's got several plugins:
https://github.com/PaulLeCam/react-leaflet/blob/master/docs/Plugins.md

But none to handle the geolocation thing... So a development is required. Though I think we'd better create a plugin on its own, rather than coding it in osm-ui-react. That way, the new plugin will be available to people already using react-leaflet.

What do you think about it?

P.S.: Sorry for the delay of my input... ;)

**Comment by PanierAvide** [comment]
Well it would be the best option. But it's more work than just integrating an existing plugin (well for Leaflet and not react-leaflet).

**Comment by GuillaumeAmat** [comment]
Yes indeed... May we keep that in mind as a future improvement?

About your commit, it seems to do the job :) Thanks!

**Comment by bleucitron** [comment]
What is the actual current status of this issue ?
Is it still "Doing" ? If not, please update the project accordingly.

**Comment by GuillaumeAmat** [comment]
@PanierAvide began the work, you can see it in the storybook, but I remember some issues about the (un)mount scenario...
