### ISSUE TITLE
Add component : Notifications

### ISSUE THREAD

**Issue by GuillaumeAmat** [osm-ui/react#10]
As an MVP component, I suggest to provide some basic notifications:

* Duplicate the style of the Sidebar component
  * And use the same animation delays
  * On large screens, add borders to the borders that are not on the viewport edge
  * max-width: 500px
* Have a delay prop
  * 4000 ms by default
  * Can be set to 0 for no delay
* Have a position prop: top, top-right, right, etc.
* Have a direction prop: top, right, bottom, left (direction of the animation)
* Have an opened prop
* No Header/Footer handling but a simple title prop
* The content is handled by the children
* Two possible CTA props
  * No CTA: Display a cancel button
  * 1 CTA: Display the cancel button and the CTA
  * 2 CTA: Display the 2 CTA buttons
  * Set opened to false when clicking on a CTA
* No cross to close the notification

**Comment by bleucitron** [comment]
### The `delay` prop
Is it the delay before it appears ? 4000 ms by default seems a bit long to me, 2000 ms might be better. 

### The `opened` prop
I don't see the purpose of having an `opened` prop.
Do you intend to make this component a permanent one, like the sidebar ?
I would rather have it mounted only when necessary (decision made as `state` at `Root` level), and in that case there is no need for this prop.
If you still prefer to have it mounted permanently, I would suggest to have `opened` as local `state` rather.

### Children
Do we really need to implement children ?
Basically, this component would only be a title, some text, maybe an icon, and CTA buttons, all passed as props.
Making the Notification potentially more complex make little sense to me (why not use the Modal then ?)

### Closing
Why would you not have a cross to close it ? It uses less space than a "Cancel" button.
The cross would not be available if a CTA is required (in the case of 2 CTAs).

### Props suggestions
- `type`: "Error", "Warning", "Validation"..., this would serve as "title". A icon could be display along with the type.
- `text`: the actual text to display
- `delay`: the delay before it appears, in ms
- `position`
- `direction`
- _optional_ `ctas`: a list of CTAs, display only the first 2, log a warning if more than 2 CTAs.

**Comment by GuillaumeAmat** [comment]
The `delay` is about the time before closing a notification when the user does not interact with it. I don't think an appearing delay is relevant in the notification case. But I certainly am missing a point... You can distinguish the two delay props if you think we have to add it.

You're right about the `opened`, it's not really appropriate here ^^

I really like the children approach because it has an easier readability IMHO... You can add other components to have a "rich" content with your own disposition. You can do that with props but, I don't know, I prefer the other way :)
By the way it is the approach used in the Sidebar component.

In the mobile world you rarely meet close cross in the UI. Maybe because it is tricky to reach it with your finger when walking the field. I try to stick with that kind of code and I would like to add swipe/gesture handling to open/dismiss/close things in the UI.
About the _no cancel button when two CTAs_ thing, I was thinking about to give the responsability to the developer to close the notification when the user is clicking on a CTA rather than display three buttons for example (2 CTAs and the cancel one).

About the props suggestions:

* `type`: great, just stick to the actual _context_ used in the other components for the moment (eg: Alert component)
* `text`: see the comments above
* `delay`: see the comments above
* `position`: ok
* `direction`: ok
* `ctas`: Great for the behavior, I would prefer `callToActions` for the name though


Thank you!

**Comment by bleucitron** [comment]
> The delay is about the time before closing a notification when the user does not interact with it. I don't think an appearing delay is relevant in the notification case. But I certainly am missing a point... 

You're not. I misunderstood the `delay` prop. I get it now, and it's so obvious that I feel stupid :/

> You can add other components to have a "rich" content with your own disposition.
> By the way it is the approach used in the Sidebar component.

While it makes sense for `Sidebar` to have rich content, I can't find a proper reason for rich `Notifications`, but I totally can be convinced with examples.

> In the mobile world you rarely meet close cross in the UI. Maybe because it is tricky to reach it with your finger when walking the field. I try to stick with that kind of code and I would like to add swipe/gesture handling to open/dismiss/close things in the UI.

I kind of agree. But I believe you could think of a design where the cross would be accessible even on mobile and still take less space than a "Cancel" button.
The touch capability would be the perfect option indeed, but it seems this is not yet supported on IE and Safari (and Opera).
For the time being, I will try different approaches and I'll let you know.

> I was thinking about to give the responsability to the developer to close the notification when the user is clicking on a CTA

What if the user never clicks on a CTA ? Does the notification stay forever ? If the notification requires the user to react, shouldn't we display the Modal instead, so that the user has no other option than to react ?
Or if there is a notification with 2 choices, but the choice can wait, we might close it after an extended delay (say 10-20s) and leave it available in a possible "Notification Center". This would imply adding an `pending` prop to the component so that it stays alive pending the user to react.
Anyway, we can leave this for further thinking. I'll implement the component so that it stays on until a CTA is clicked.

**Comment by GuillaumeAmat** [comment]
Oh... You're totally right on the last point ^^' I did not think about that.
Ok, for that point and the previous one I think that adding a cross is reasonable :P 

I don't really have good examples for the rich content subject. Just that the current API is to use children for the main content rather than to use props... I would prefer to stick with the same choices for all the components.

**Comment by bleucitron** [comment]
Alright, I'll do that.

Bringing up another topic: Transitions.

With current `CSSTransitionGroup`, it is not possible to fade out and then unmount the component.
The API has changed with [version 2.0](https://github.com/reactjs/react-transition-group/tree/master) of the package to allow that.

You can check out examples [here](https://reactcommunity.org/react-transition-group/).
The `CSSTransition` component is quite similar to the current classname approach, but I can't get to make it work properly with our code.
The `Transition` component works with the `style` attribute, and I find it more elegant in the end.

I would like to have your opinion on the (draft) code I'm working on:
https://github.com/iOiurson/react/blob/notification/src/components/Notification/Notification.jsx

I think we need to apply the v2 version of ReactTransitionGroup in any case, and there will be some adjustments on current code anyway, whether we agree on `Transition` philosophy rather than `CSSTransition`.

**Comment by GuillaumeAmat** [comment]
Great! The new Transition approach is far better indeed. Go for it!

Your draft seems good, but it remerbers me that we did not talk about the _pause_ when the user hover over the notification. The `setTimeout` of the `onEntered` prop has to be cleared when the user hover the notification, and get relaunched when he leaves it. Do you agree with that?

**Comment by bleucitron** [comment]
Oopsy, this is clearly important !
Yes obviously, I'll do that.

**Comment by bleucitron** [comment]
I'm about to push some code.
I have a problem with tests though...

Testing my `Notification` component, I get the following error.
I do not use `jQuery`, nor `Bootstrap` (or I think I'm not).
What is weird is that I have updated the component `Modal` (that uses `Transition too`) and there is no problem...

Does this problem ring a bell ?

```
 FAIL  src/components/Notification/__tests__/Notification.test.jsx
  ● Test suite failed to run

    ReferenceError: jQuery is not defined

      at Object.<anonymous> (node_modules/bootstrap/js/transition.js:59:3)
      at Object.<anonymous> (node_modules/bootstrap/dist/js/npm.js:2:1)
      at Object.<anonymous> (src/index.js:2:1)
      at Object.<anonymous> (src/components/Notification/Notification.jsx:9:14)
      at Object.<anonymous> (src/components/Notification/index.js:1:185)
      at Object.<anonymous> (src/components/Notification/__tests__/Notification.test.jsx:3:9)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:125:13)
      at process.emit (events.js:213:7)
      at emit (internal/child_process.js:768:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by GuillaumeAmat** [comment]
Bootstrap is used in the project and it requires jquery... I know...

Can I see your branch?

**Comment by bleucitron** [comment]
I kind of fixed it...
The problem comes from `src/components/index.js`, that requires jQuery and Bootstrap.

I fixed it by importing directly `src/component/Button/index.js` rather than `src/component/index.js`, but would love another idea.

**Comment by GuillaumeAmat** [comment]
It's weird, all the other tests use the index import and there is no problem :/ I will check it when the PR will be ready.
