### ISSUE TITLE
Add component : Color picker

### ISSUE THREAD

**Issue by GuillaumeAmat** [osm-ui/react#11]

**Comment by bleucitron** [comment]
This library could do the trick: https://casesandberg.github.io/react-color/

**Comment by GuillaumeAmat** [comment]
The outlook is great! And it gives all the colors to the user, with predefined colors!

Great 🕶

**Comment by bleucitron** [comment]
For now, i've chosen to use the Twitter color picker, because it feels simple.
Although i understand the need for all icons in the Icon Picker, here about 10 default colors and the input for hexa should be enough fort 99% of the cases.

It doesn't feel necessary to provide the full picker with all shades and stuff, we're not building Photoshop.

https://github.com/osm-ui/react/blob/color-picker/src/components/ColorPicker/ColorPicker.jsx

**Comment by GuillaumeAmat** [comment]
Agreed with the Photoshop point, even though some folks asked me to add more color in the past. At least now they will be able to add an hexa value.

And in the worst case we will be able to put another picker from the available list.
