### ISSUE TITLE
Reduce coveralls noisy comments

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#16]
Is it possible to add coverall comment about coverage only when merging or something ? I find it annoying to have comments (and subsequent notification mails) every time I push a commit...

We could also try to forbid pushes when the coverage is reduced via git hooks...

**Comment by GuillaumeAmat** [comment]
Ok I just did some tweaks in the Coveralls settings. I don't know if the notifications will be less noisy though, the settings are not very clear...

Also, there are two parameters to fail the coverage based on the new percentage:
- Coverage Threshold for failure (currently not set)
- Coverage Decrease Threshold for failure (set to 1% since now)

I close the issue for now, feel free to reopen it if you're still annoyed by the notifications.
