### ISSUE TITLE
When should we use tests ?

### ISSUE THREAD

**Issue by bleucitron** [osm-ui/react#24]
It is my understanding that we currently run our tests twice, at `precommit` with the `ci` option, and at `prepush`, which I added some time ago.

(I might be wrong though).

I find it more convenient to test at `prepush`. Maybe we should only keep this one ?

**Comment by GuillaumeAmat** [comment]
In my opinion, running the tests on `prepush` do twice the job... twice.

Currently the tests are played on the `precommit` hook and only for the modified files, which is really fast. So the `prepush` is sort of *useless* as the tests have already been launched once. Furthermore, the `prepush` hook runs *all* the tests, even on the files that did not have been modified.

The second duplication concerns the CI. It is here to control that the whole project is stable on a particular branch. So it already runs all the tests at every push, in a way that the developer is not bothered by the wait of the end of the tests.

With just the `precommit` and the CI, we cover all the case and we have the fastest way to do it.

I thought that you were in the need of the `prepush` hook and I wanted to not force my workflow to other people, so I did not talk about that earlier but that issue is here now so... That's my vision of the subject ^^

What do you think about that?

**Comment by bleucitron** [comment]
I don't understand how the test on `precommit` with `lint-staged` is relevant...
Say you have `MyComponent.jsx` and `MyComponent.test.jsx`.

If I modify and `git add` only `MyComponent.jsx` and NOT the corresponding test file, no test will be run, and I might miss out that my code broke...

I might be misunderstanding something, but to me it's best to test all the files (in case something unexpected broke), and `prepush` seems a good moment to do so to avoid tests to be run too often.

The alternative to testing all the files would be to test only the test files that use the files we `git add`ed, but I'm sure this is even possible.

**Comment by GuillaumeAmat** [comment]
It's relevant when you do not forget to put the right option in the `lint-staged` command ^^
I forgot to put `--findRelatedTests` which is here to specifically address your issue. I have found an article explaining well the entire reflection: https://benmccormick.org/2017/02/26/running-jest-tests-before-each-git-commit/

I will put the option in the command.

By the way, IMO, running all the tests at `prepush` is just a waste of time for the developer as they are already ran in the CI right after the `push`. That's why CI exists after all.

**Comment by GuillaumeAmat** [comment]
Ok, I put the `--findRelatedTests` option to the `precommit` hook and remove the `prepush` hook. I really think that the best move as the developer don't have to wait and all tests are always ran.

Feel free to continue the discussion if you think I miss a point. I will be pleased to find a consensus :)

**Comment by bleucitron** [comment]
I get the impression that `--findRelatedTests` does not work efficiently...
For a simple modification of the `src/components/Notification/Notification.jsx` file, the `precommit` hook ran 60 tests although it should have only one... which kind of slows down the committing process.

Did you experience issues similar to this one ?

**Comment by GuillaumeAmat** [comment]
Do those 60 tests are really unrelated to the modified file?

Maybe the global `index.js` file is the guilty in your issue. As we import the components from it in the tests and it imports all the components... Maybe we should directly import the components without it.

**Comment by bleucitron** [comment]
This might be it, I had the feeling that all component tests were run.
I will investigate tomorrow.

**Comment by bleucitron** [comment]
This is indeed the problem: having all components imported in a single `index.js` file.
This links all the components together, then the `findRelatedTests` option understands all component tests should be run.

I suggest we get rid of the global `index.js` file, and import themes and components directly from their origin folder.

But I do not know the implications of such decision concerning the `jquery`, `bootstrap` and such imports of `index.js`...

**Comment by GuillaumeAmat** [comment]
The global `index.js` has to remain in the project. It is the entry point for the developers willing to import our components.

That said, our tests must import the components from the direct path instead of the global `index.js`. That way the issue should be fixed.

**Comment by bleucitron** [comment]
I tried that first, and it doesn't help.
I'll try again just to check.

**Comment by GuillaumeAmat** [comment]
So maybe find a way to ignore `src/index.js` from the tests?

**Comment by bleucitron** [comment]
With `jest-styled-component`, all tests are still run at `lint-staged`, but at least many less tests fail because of changed `classnames` in snapshots.

**Comment by GuillaumeAmat** [comment]
Great, I didn't know that module thanks.
